# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78ac64bbe4d5bc60bd9949eedb7f6e1620e59295b29fe39e699d46523ba3dfd9286ee7eccbb6c772cab4c37561e029c9c15a4ae9090f1aef77e7c32efb34cbb7

test:
  secret_key_base: 058151810be1df5805cb5c996c09f04095f1b5cf1173e264836c6e665fc3e7c8e4bfa789a0da246f165461b8df768a8a2d912732e35cb3680b79cf417d174a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
